name: Run Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:  
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.38f1
          - 6000.0.20f1
    steps:
      - name: Get Repository Name
        run: |
          echo "PROJECT_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.PROJECT_NAME }}/Library
          key: Library-${{ env.PROJECT_NAME }}
          restore-keys: |
            Library-

      # - name: Authenticate UPM
      #   run: |
      #     mkdir /home/runner/work/_temp/_github_home
      #     cd /home/runner/work/_temp/_github_home
      #     echo "[npmAuth.\"https://npm.pkg.github.com/@${{ github.repository_owner }}\"]" >> .upmconfig.toml
      #     echo "token = \"${{ secrets.PACKAGE_TOKEN }}\"" >> .upmconfig.toml
      #     echo "alwaysAuth = true" >> .upmconfig.toml

      - name: Run Tests
        id: tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: All
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ${{ env.PROJECT_NAME }}
          checkName: Test Results (${{ matrix.unityVersion }})
          customParameters: -coverageOptions useProjectSettings

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results (${{ matrix.unityVersion }})
          path: ${{ steps.tests.outputs.artifactsPath }}

      # - name: Upload Coverage Results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: Coverage Results (${{ matrix.unityVersion }})
      #     path: ${{ steps.tests.outputs.coveragePath }}