name: Run Unit Tests

on:
  push:
    paths:
      - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:

jobs:  
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.27f1
          - 2022.3.2f1
    steps:
      - name: Get Repository Name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.REPO_NAME }}/Library
          key: Library-${{ matrix.unityVersion }}
          restore-keys: Library-

      # - name: Authenticate UPM
      #   run: |
      #     mkdir /home/runner/work/_temp/_github_home
      #     cd /home/runner/work/_temp/_github_home
      #     echo "[npmAuth.\"https://npm.pkg.github.com/@${{ github.repository_owner }}\"]" >> .upmconfig.toml
      #     echo "token = \"${{ secrets.PACKAGE_TOKEN }}\"" >> .upmconfig.toml
      #     echo "alwaysAuth = true" >> .upmconfig.toml

      - name: Run Tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: All
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ env.REPO_NAME }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -coverageOptions useProjectSettings

      # - name: Upload Coverage Report
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: Coverage Report
      #     path: ${{ steps.tests.outputs.coveragePath }}
