name: Run Unit Tests

on:
  push:
    paths:
      - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:

jobs:  
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2021.3.27f1
          - 2022.3.2f1
        testMode:
          - All
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.event.repository.name }}/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ github.event.repository.name }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}